/* eslint-disable */
/**
 * This file was automatically generated by json-schema-to-typescript.
 * DO NOT MODIFY IT BY HAND. Instead, modify the source JSONSchema file,
 * and run json-schema-to-typescript to regenerate this file.
 */

export type GenericNotOkResponse = ServerError | ApplicationError;

export interface ServerError {
    statusCode: number;
    message: string;
    [k: string]: unknown;
}
export interface ApplicationError {
    statusCode?: number;
    message?: string;
    [k: string]: unknown;
}
