// AUTOGENERATED - DO NOT EDIT
/* eslint-disable */

export const Schema = {
	GetMessagesOkResponse: require('./messages/get-messages-ok-response-schema.json'),
	GetMessagesRequestBody: require('./messages/get-messages-request-body-schema.json'),
	GetMessagesRequestParams: require('./messages/get-messages-request-params-schema.json'),
	SendMessageOkResponse: require('./messages/send-message-ok-response-schema.json'),
	SendMessageRequestBody: require('./messages/send-message-request-body-schema.json'),
	SendMessageRequestParams: require('./messages/send-message-request-params-schema.json'),
	NotOkResponse: require('./not-ok-response-schema.json'),
};
